import { colors } from "@/theme";
import { Platform, StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.backgroundMain,
  },
  content: {
    paddingHorizontal: (412 - 351) / 2,
    paddingTop: Platform.OS === "android" ? 72 : 84,
    paddingBottom: 40,
    alignItems: "center",
    flexGrow: 1,
  },
  title: {
    alignSelf: "flex-start",
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 32,
  },
  subtitle: {
    alignSelf: "flex-start",
    marginTop: 8,
    color: "#FFFFFF80",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
  },
  inputWrapper: {
    marginTop: 40,
    width: 351,
  },
  hint: {
    alignSelf: "stretch",
    textAlign: "center",
    marginTop: 25,
    marginBottom: 24,
    color: "#FFFFFF80",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
  },
  signInButton: {
    width: 351,
    height: 64,
    borderRadius: 16,
    backgroundColor: colors.pressableActive3,
    alignItems: "center",
    justifyContent: "center",
  },
  signInButtonText: {
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    width: 351,
    marginTop: 32,
    marginBottom: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#ffffff",
  },
  dividerText: {
    marginHorizontal: 12,
    color: "#FFFFFF80",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
  },
  socialList: {
    width: 351,
    gap: 14,
  },
  container: {
    width: 351,
    borderWidth: 1,
    borderColor: "#ffffff",
    borderRadius: 16,
    paddingVertical: 12,
    justifyContent: "center",
  },
  containerValid: {
    borderColor: "#22C55E",
  },
  containerInvalid: {
    borderColor: "#EF4444",
  },
  label: {
    position: "absolute",
    top: -9,
    left: 16,
    backgroundColor: colors.backgroundMain,
    paddingHorizontal: 6,
    color: "#FFFFFF",
    fontFamily: "Inter_400Regular",
    fontSize: 12,
  },
  regionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 36,
    paddingHorizontal: 16,
  },
  regionText: {
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
  },
  divider: {
    height: 1,
    backgroundColor: "#ffffff",
    marginVertical: 12,
    width: "100%",
  },
  phoneRow: {
    flexDirection: "row",
    alignItems: "center",
    height: 36,
    paddingHorizontal: 16,
  },
  phoneIcon: {
    marginRight: 10,
  },
  phoneInput: {
    flex: 1,
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    padding: 0,
    height: 36,
  },
  emailInput: {
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    padding: 0,
    paddingHorizontal: 16,
    height: 36,
  },
  passwordInput: {
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    padding: 0,
    paddingHorizontal: 16,
    height: 36,
  },
  requirementsList: {
    width: 335,
    alignSelf: "center",
    marginTop: 24,
  },
  requirementRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  bullet: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#FFFFFF80",
    marginRight: 10,
  },
  bulletValid: {
    backgroundColor: "#22C55E",
  },
  bulletInvalid: {
    backgroundColor: "#EF4444",
  },
  requirementText: {
    color: "#FFFFFF80",
    fontFamily: "Inter_400Regular",
    fontSize: 13,
  },
  requirementValid: {
    color: "#22C55E",
  },
  requirementInvalid: {
    color: "#EF4444",
  },
  bottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 335,
    alignSelf: "center",
    marginTop: "auto",
    paddingBottom: 20,
  },
  backText: {
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
  },
  nextButton: {
    width: 87,
    height: 52,
    borderRadius: 28,
    backgroundColor: colors.pressableActive1,
    alignItems: "center",
    justifyContent: "center",
  },
  nextButtonText: {
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: 300,
    backgroundColor: "#334155",
    borderRadius: 16,
    padding: 16,
  },
  modalTitle: {
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
    fontSize: 18,
    marginBottom: 12,
    textAlign: "center",
  },
  modalOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#475569",
  },
  modalOptionText: {
    color: "#ffffff",
    fontFamily: "Inter_400Regular",
    fontSize: 16,
  },
  modalOptionSelected: {
    color: "#3B82F6",
    fontFamily: "Inter_600SemiBold",
  },
  dropdownList: {
    marginTop: 4,
    marginHorizontal: 8,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 12,
    overflow: "hidden",
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  dropdownItemSelected: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
  },
  dropdownItemText: {
    color: "#FFFFFF80",
    fontFamily: "Inter_400Regular",
    fontSize: 14,
  },
  dropdownItemTextSelected: {
    color: "#ffffff",
    fontFamily: "Inter_600SemiBold",
  },
});
